version: "3.9"
services:
  svg-converter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["poetry", "run", "python", "-m", "svg_converter"]
